name: my_gym_lifts
description: My Gym Lifts (iOS and Android)

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.0.13
  auto_size_text: ^3.0.0
  speech_to_text: ^5.4.2
  flutter_cache_manager: ^3.3.0
  http: ^0.13.3
  statusbarz: ^1.0.6
  device_info: ^2.0.3
  flutter_calendar_carousel: ^2.1.0
  video_player: ^2.2.18
  flutter_spinkit: ^5.1.0
  after_layout: ^1.1.0
  image_picker: ^0.8.4+6
  provider: ^6.0.2
  wave: ^0.2.0
  permission_handler: ^8.3.0
  camera: ^0.9.4+10
  path: ^1.8.0
  path_provider: ^2.0.8
  shimmer: ^2.0.0
  open_file: ^3.2.1
  video_editor: ^1.2.3
  photo_manager: ^1.3.10
  helpers: ^1.1.4
  gallery_saver: ^2.3.2
  rflutter_alert: ^2.0.4
  dismissible_page: ^0.6.4
  uuid: ^3.0.5
  share_plus: ^3.0.5
  pull_to_refresh: ^2.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/

  # Fonts
  fonts:
    - family: MyGymLiftsIcons
      fonts:
        - asset: assets/fonts/MyGymLiftsIcons.ttf
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
